package com.fcant.dl.bean;

import lombok.Data;

/**
 * Info
 *
 * encoding:UTF-8
 * @author Fcant
 * @date 下午 19:57 2019-08-13/0013
 */
@Data
public class Info {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.id
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_type
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private Integer infoType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_title
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String infoTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_content
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String infoContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_linkman
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String infoLinkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_phone
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String infoPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_email
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String infoEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_data
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String infoData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_check
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String infoCheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_payfor
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String infoPayfor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_status
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String infoStatus;

}