package com.fcant.dl.bean;

import lombok.Data;

import java.util.Date;

/**
 * Info
 *
 * encoding:UTF-8
 * @author Fcant
 * @date 下午 19:57 2019-08-13/0013
 */
@Data
public class Info {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.id
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_type
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private Integer infoType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_title
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String infoTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_content
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String infoContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_linkman
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String infoLinkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_phone
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String infoPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_email
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String infoEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_data
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private Date infoData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_check
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String infoCheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_payfor
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String infoPayfor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_info.info_status
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String infoStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_info.id
     *
     * @return the value of tb_info.id
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_info.id
     *
     * @param id the value for tb_info.id
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_info.info_type
     *
     * @return the value of tb_info.info_type
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public Integer getInfoType() {
        return infoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_info.info_type
     *
     * @param infoType the value for tb_info.info_type
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public void setInfoType(Integer infoType) {
        this.infoType = infoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_info.info_title
     *
     * @return the value of tb_info.info_title
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public String getInfoTitle() {
        return infoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_info.info_title
     *
     * @param infoTitle the value for tb_info.info_title
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public void setInfoTitle(String infoTitle) {
        this.infoTitle = infoTitle == null ? null : infoTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_info.info_content
     *
     * @return the value of tb_info.info_content
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public String getInfoContent() {
        return infoContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_info.info_content
     *
     * @param infoContent the value for tb_info.info_content
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public void setInfoContent(String infoContent) {
        this.infoContent = infoContent == null ? null : infoContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_info.info_linkman
     *
     * @return the value of tb_info.info_linkman
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public String getInfoLinkman() {
        return infoLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_info.info_linkman
     *
     * @param infoLinkman the value for tb_info.info_linkman
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public void setInfoLinkman(String infoLinkman) {
        this.infoLinkman = infoLinkman == null ? null : infoLinkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_info.info_phone
     *
     * @return the value of tb_info.info_phone
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public String getInfoPhone() {
        return infoPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_info.info_phone
     *
     * @param infoPhone the value for tb_info.info_phone
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public void setInfoPhone(String infoPhone) {
        this.infoPhone = infoPhone == null ? null : infoPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_info.info_email
     *
     * @return the value of tb_info.info_email
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public String getInfoEmail() {
        return infoEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_info.info_email
     *
     * @param infoEmail the value for tb_info.info_email
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public void setInfoEmail(String infoEmail) {
        this.infoEmail = infoEmail == null ? null : infoEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_info.info_data
     *
     * @return the value of tb_info.info_data
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public Date getInfoData() {
        return infoData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_info.info_data
     *
     * @param infoData the value for tb_info.info_data
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public void setInfoData(Date infoData) {
        this.infoData = infoData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_info.info_check
     *
     * @return the value of tb_info.info_check
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public String getInfoCheck() {
        return infoCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_info.info_check
     *
     * @param infoCheck the value for tb_info.info_check
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public void setInfoCheck(String infoCheck) {
        this.infoCheck = infoCheck == null ? null : infoCheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_info.info_payfor
     *
     * @return the value of tb_info.info_payfor
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public String getInfoPayfor() {
        return infoPayfor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_info.info_payfor
     *
     * @param infoPayfor the value for tb_info.info_payfor
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public void setInfoPayfor(String infoPayfor) {
        this.infoPayfor = infoPayfor == null ? null : infoPayfor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_info.info_status
     *
     * @return the value of tb_info.info_status
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public String getInfoStatus() {
        return infoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_info.info_status
     *
     * @param infoStatus the value for tb_info.info_status
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public void setInfoStatus(String infoStatus) {
        this.infoStatus = infoStatus == null ? null : infoStatus.trim();
    }
}