package com.fcant.dl.bean;

import lombok.Data;

/**
 * Type
 *
 * encoding:UTF-8
 * @author Fcant
 * @date 下午 19:57 2019-08-13/0013
 */
@Data
public class Type {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_type.type_sign
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private Integer typeSign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_type.type_name
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_type.type_intro
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String typeIntro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_type.type_sign
     *
     * @return the value of tb_type.type_sign
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public Integer getTypeSign() {
        return typeSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_type.type_sign
     *
     * @param typeSign the value for tb_type.type_sign
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public void setTypeSign(Integer typeSign) {
        this.typeSign = typeSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_type.type_name
     *
     * @return the value of tb_type.type_name
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_type.type_name
     *
     * @param typeName the value for tb_type.type_name
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_type.type_intro
     *
     * @return the value of tb_type.type_intro
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public String getTypeIntro() {
        return typeIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_type.type_intro
     *
     * @param typeIntro the value for tb_type.type_intro
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public void setTypeIntro(String typeIntro) {
        this.typeIntro = typeIntro == null ? null : typeIntro.trim();
    }
}