package com.fcant.dl.bean;

import lombok.Data;

/**
 * User
 *
 * encoding:UTF-8
 * @author Fcant
 * @date 下午 19:57 2019-08-13/0013
 */
@Data
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.id
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_name
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_password
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_type
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_statue
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    private String userStatue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.id
     *
     * @return the value of tb_user.id
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.id
     *
     * @param id the value for tb_user.id
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_name
     *
     * @return the value of tb_user.user_name
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_name
     *
     * @param userName the value for tb_user.user_name
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_password
     *
     * @return the value of tb_user.user_password
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_password
     *
     * @param userPassword the value for tb_user.user_password
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_type
     *
     * @return the value of tb_user.user_type
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_type
     *
     * @param userType the value for tb_user.user_type
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_statue
     *
     * @return the value of tb_user.user_statue
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public String getUserStatue() {
        return userStatue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_statue
     *
     * @param userStatue the value for tb_user.user_statue
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    public void setUserStatue(String userStatue) {
        this.userStatue = userStatue == null ? null : userStatue.trim();
    }
}