package com.fcant.gh.mapper;

import com.fcant.gh.bean.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUSER
     *
     * @mbg.generated Thu Aug 29 00:07:49 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUSER
     *
     * @mbg.generated Thu Aug 29 00:07:49 GMT+08:00 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUSER
     *
     * @mbg.generated Thu Aug 29 00:07:49 GMT+08:00 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUSER
     *
     * @mbg.generated Thu Aug 29 00:07:49 GMT+08:00 2019
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUSER
     *
     * @mbg.generated Thu Aug 29 00:07:49 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUSER
     *
     * @mbg.generated Thu Aug 29 00:07:49 GMT+08:00 2019
     */
    int updateByPrimaryKey(User record);
}