package com.fcant.gh.bean;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUSER.ID
     *
     * @mbg.generated Thu Aug 29 00:07:49 GMT+08:00 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUSER.USER_NAME
     *
     * @mbg.generated Thu Aug 29 00:07:49 GMT+08:00 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUSER.USER_PHONE
     *
     * @mbg.generated Thu Aug 29 00:07:49 GMT+08:00 2019
     */
    private String userPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUSER.ID
     *
     * @return the value of STUSER.ID
     *
     * @mbg.generated Thu Aug 29 00:07:49 GMT+08:00 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUSER.ID
     *
     * @param id the value for STUSER.ID
     *
     * @mbg.generated Thu Aug 29 00:07:49 GMT+08:00 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUSER.USER_NAME
     *
     * @return the value of STUSER.USER_NAME
     *
     * @mbg.generated Thu Aug 29 00:07:49 GMT+08:00 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUSER.USER_NAME
     *
     * @param userName the value for STUSER.USER_NAME
     *
     * @mbg.generated Thu Aug 29 00:07:49 GMT+08:00 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUSER.USER_PHONE
     *
     * @return the value of STUSER.USER_PHONE
     *
     * @mbg.generated Thu Aug 29 00:07:49 GMT+08:00 2019
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUSER.USER_PHONE
     *
     * @param userPhone the value for STUSER.USER_PHONE
     *
     * @mbg.generated Thu Aug 29 00:07:49 GMT+08:00 2019
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }
}