package com.fcant.dl.mapper;

import com.fcant.dl.bean.Info;

import java.util.List;

/**
 * InfoMapper
 *
 * encoding:UTF-8
 * @author Fcant
 * @date 下午 19:14 2019-08-21/0021
 */
public interface InfoMapper {

    /**
     * 根据信息ID查询信息
     *
     * @param info -信息ID
     * @return Info
     * @author Fcant
     * @date 下午 19:35 2019-08-24/0024
     */
    Info selectInfoById(Info info);

    /**
     * 全字匹配查询
     *
     * @param info 查询的对象
     * @return MsgUtil
     * @author Fcant
     * @date 下午 23:28 2019-08-21/0021
     */
    List<Info> selectByAll(Info info);

    /**
     * 模糊查询
     *
     * @param info 查询的对象
     * @return MsgUtil
     * @author Fcant
     * @date 下午 23:27 2019-08-21/0021
     */
    List<Info> selectByLike(Info info);

    /**
     * 查询所有信息
     *
     * @return List<Info>
     * @author Fcant
     * @date 下午 19:14 2019-08-21/0021
     */
    List<Info> selectAllByCheckPay(Info info);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_info
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_info
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    int insert(Info record);

    /**
     * 插入新的信息
     *
     * @param info 信息
     * @return int
     * @author Fcant
     * @date 下午 19:57 2019-08-19/0019 
     */
    int insertNewInfo(Info info);

    /**
     * 根据ID查询信息
     *
     * @param info id
     * @return Info
     * @author Fcant
     * @date 下午 20:26 2019-08-24/0024
     */
    Info selectById(Info info);

    /**
     * 更新信息根据ID
     *
     * @param info id、check、pay
     * @return int
     * @author Fcant
     * @date 下午 20:25 2019-08-24/0024
     */
    int updateInfoById(Info info);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_info
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    int updateByPrimaryKey(Info record);
}