package com.fcant.dl.mapper;

import com.fcant.dl.bean.Type;

public interface TypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_type
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer typeSign);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_type
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    int insert(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_type
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    int insertSelective(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_type
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    Type selectByPrimaryKey(Integer typeSign);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_type
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_type
     *
     * @mbg.generated Tue Aug 13 19:48:59 GMT+08:00 2019
     */
    int updateByPrimaryKey(Type record);
}